microsoft/TypeScript-Website

- src/_data/doctoc.yml
Closes microsoft/TypeScript-Handbook#994
Closes microsoft/TypeScript-Handbook#1037
> Add link to Utility Types page

- src/_includes/anchor_headings.html
- src/assets/scss/_global.scss
- src/assets/scss/docs.scss
Links to https://github.com/microsoft/TypeScript-Handbook/pull/1108
> More a11y issues

- Examples/en/TypeScript/Meta-Types/Conditional Types.ts
- Examples/en/TypeScript/Primitives/Unknown and Never.ts
After some discussion with @orta.
> Some fixes

- Examples/en/JavaScript/JavaScript Essentials/Objects and Arrays.ts
- Examples/en/Playground/Config/JavaScript Playgrounds.js
- Examples/en/Playground/Config/New Compiler Defaults.ts
- Examples/en/Playground/Language/Automatic Type Acquisition.ts
- Examples/en/Playground/Language/Fixits.ts
- Examples/en/Playground/Tooling/Mobile Support.ts
- Examples/en/Playground/Tooling/Sharable URLs.ts
- Examples/en/Playground/Tooling/TypeScript Versions.ts
- Examples/scripts/generateTOC.js
> Add documentation about the new features of the playground to the playground

- Examples/en/JavaScript/Functions with JavaScript/Generic Functions.ts
> Fix a couple of typos in GenericFunctions example

- src/_docs/home.html
TypeScript is not a subset of JavaScript, it is a superset.
> Replace the word "subset" with "superset"

- packages/handbook-v1/en/tutorials/Migrating from JavaScript.md
> fixes some issues I encountered trying to configure a project to use typescript with webpack

- packages/tsconfig-reference/copy/en/options/include.md
- packages/tsconfig-reference/copy/en/options/removeComments.md
Fixes the minor issues mentioned in #224
> docs(tsconfig): Fix include and removeComments

- packages/tsconfig-reference/copy/en/options/isolatedModules.md
- packages/tsconfig-reference/copy/ja/options/isolatedModules.md
A part of #220. I translated https://www.typescriptlang.org/v2/en/tsconfig#isolatedModules .
> Translate isolatedModules into ja

- packages/handbook-v1/en/tutorials/DOM Manipulation.md
Adds a new tutorial on DOM Manipulation using TypeScript _lib.dom.d.ts_ 👍
> add dom manipulation doc

- packages/tsconfig-reference/copy/ja/categories/Command_line_Options_6171.md
- packages/tsconfig-reference/copy/ja/categories/Experimental_Options_6177.md
- packages/tsconfig-reference/copy/ja/options/emitDecoratorMetadata.md
- packages/tsconfig-reference/copy/ja/options/experimentalDecorators.md
- packages/tsconfig-reference/copy/ja/options/preserveWatchOutput.md
- packages/tsconfig-reference/copy/ja/options/pretty.md
This is a part of #220 .
I translated tsconfig reference docs under 
- https://www.typescriptlang.org/v2/en/tsconfig#Experimental_Options_6177
- Comparison for original docs: https://github.com/microsoft/TypeScript-Website/commit/2e990c2f5bc00bb877ae46f2d1565295cd1e80e4
- https://www.typescriptlang.org/v2/en/tsconfig#Command_line_Options_6171
- Comparison for original docs: https://github.com/microsoft/TypeScript-Website/commit/fdd0d5b72dc97758463f8ecb073aa427d079d57c
> Translate tsconfig experimental and CLI options into ja

- packages/typescriptlang-org/src/components/index/EditorExamples.tsx
Thanks for the awesome new website!
Just a quick PR to fix up the React example.
> Fix React example

- packages/tsconfig-reference/copy/ja/options/assumeChangesOnlyAffectDirectDependencies.md
- packages/tsconfig-reference/copy/ja/options/emitDeclarationOnly.md
- packages/tsconfig-reference/copy/ja/options/extendedDiagnostics.md
- packages/tsconfig-reference/copy/ja/options/generateCpuProfile.md
- packages/tsconfig-reference/copy/ja/options/importsNotUsedAsValues.md
part of #220 
I translated some advenced options into ja
Comparison for original docs: 9e1dd0e
https://www.typescriptlang.org/v2/en/tsconfig#extendedDiagnostics
> Translate some advanced options into ja

- packages/typescriptlang-org/gatsby-config.js
- packages/typescriptlang-org/package.json
- packages/typescriptlang-org/src/redirects/setupRedirects.ts
- yarn.lock
- 1, the redirects weren't actually being called
- 2, redirects in gatsby need a plugin do to work 
So, it would have been broken either way :D - I left a note in the gatsby issues https://github.com/gatsbyjs/gatsby/issues/22299
Fixes #345 #343
> Make redirects work

- packages/handbook-v1/en/release notes/TypeScript 3.8.md
> Fix TypeScript 3.8 release notes formatting issue

- packages/typescriptlang-org/src/components/layout/main.scss
| Before | After |
|--------|------|
| <img width="349" alt="Screen Shot 2020-03-30 at 2 35 12 PM" src="https://user-images.githubusercontent.com/3277153/77964337-b7f0ec00-7293-11ea-9159-a40e5851ada7.png"> | <img width="354" alt="Screen Shot 2020-03-30 at 2 35 29 PM" src="https://user-images.githubusercontent.com/3277153/77964365-c7703500-7293-11ea-99b0-5804f53bbcd7.png"> |
> Add more relaxed default line height

- packages/typescriptlang-org/src/templates/handbook.scss
- packages/typescriptlang-org/src/templates/handbook.tsx
also adds an offset for the sticky nav - fixes #434
> Brings back the 3 handbook layouts and keeps the sticky aside

- packages/playground-examples/copy/en/JavaScript/External APIs/TypeScript with React.tsx
- packages/playground-examples/copy/zh/JavaScript/External APIs/TypeScript with React.tsx
- packages/typescriptlang-org/src/components/HeadSEO.tsx
- packages/typescriptlang-org/src/components/Intl.tsx
- packages/typescriptlang-org/src/components/IntlLink.tsx
- packages/typescriptlang-org/src/components/TmpLink.tsx
- packages/typescriptlang-org/src/components/VersionBar.tsx
- packages/typescriptlang-org/src/components/devNav.tsx
- packages/typescriptlang-org/src/components/display/ButtonGrid.tsx
- packages/typescriptlang-org/src/components/display/GreyButton.tsx
- packages/typescriptlang-org/src/components/handbook/NextPrev.tsx
- packages/typescriptlang-org/src/components/index/EditorExamples.tsx
- packages/typescriptlang-org/src/components/index/UpcomingReleaseMeta.tsx
- packages/typescriptlang-org/src/components/layout.tsx
- packages/typescriptlang-org/src/components/layout/CookieBanner.tsx
- packages/typescriptlang-org/src/components/layout/SiteFooter.tsx
- packages/typescriptlang-org/src/pages/branding.tsx
- packages/typescriptlang-org/src/pages/dev/playground-plugins.tsx
- packages/typescriptlang-org/src/pages/dev/typescript-vfs.tsx
- packages/typescriptlang-org/src/pages/upcoming.tsx
- packages/typescriptlang-org/src/templates/pages/community.tsx
- packages/typescriptlang-org/src/templates/pages/docs/home.tsx
- packages/typescriptlang-org/src/templates/pages/download.tsx
- packages/typescriptlang-org/src/templates/pages/empty.tsx
- packages/typescriptlang-org/src/templates/pages/tools.tsx
- packages/typescriptlang-org/src/templates/pages/why-create-typescript.tsx
> Switch docs and uses of React to namespace imports.

- packages/handbook-v1/en/Functions.md
I'm brand-new to TypeScript, so I'm not sure if this is correct, but it looked to me like these two comments were supposed to be swapped.
> Swap function type comments

- packages/handbook-v1/en/tutorials/TS for JS Programmers.md
Fix double usage of word "automatically"
> Update TS for JS Programmers.md

- packages/create-typescript-playground-plugin/index.js
- packages/create-typescript-playground-plugin/template/scripts/getDTS.js
- packages/create-typescript-playground-plugin/template/src/index.ts
- packages/playground/package.json
- packages/playground/src/ds/createDesignSystem.ts
- packages/playground/src/index.ts
- packages/playground/src/pluginUtils.ts
- packages/playground/src/sidebar/ast.ts
- packages/playground/src/sidebar/plugins.ts
- packages/playground/src/sidebar/settings.ts
- packages/playground/src/sidebar/showErrors.ts
- packages/sandbox/package.json
- packages/sandbox/src/index.ts
- packages/ts-twoslasher/README.md
- packages/ts-twoslasher/package.json
- packages/typescript-vfs/package.json
- packages/typescriptlang-org/src/components/workbench/plugins/assertions.ts
- packages/typescriptlang-org/src/copy/en/playground.ts
- packages/typescriptlang-org/src/templates/pages/docs/home.tsx
- packages/typescriptlang-org/src/templates/play.scss
- yarn.lock
New: Settings lets you enable/disable tabs
New: An off-by-default tab for showing the whole AST and handles selection between them
> Tightens up the Playground design system and adds a useful AST viewer

- packages/handbook-v1/en/Compiler Options.md
https://www.typescriptlang.org/docs/handbook/compiler-options.html
| the problem |
| ------ | 
| ![image](https://user-images.githubusercontent.com/5839225/82194844-417a7d00-9919-11ea-9b98-21df3a977b44.png) |
| ![image](https://user-images.githubusercontent.com/5839225/82194863-4b03e500-9919-11ea-9c5a-9df01bfbe055.png) |
> Use correct quotes for file extensions and settings examples

- packages/typescriptlang-org/src/lib/handbookNavigation.ts
> fix release notes navigation wrong link

- packages/handbook-v1/en/tutorials/TS for JS Programmers.md
this is broken - https://www.typescriptlang.org/handbook/literal-types.html
> Fixes broken redirect url

- packages/handbook-v1/en/tutorials/TS for the New Programmer.md
Note: there's a bunch of "issues" as comments in here, since it's nearly impossible to create an issue on a line in an md file since GH does not have an option to show the md source.  These comments should be considered separate issues, which I'll remove if rejected, or write it if accepted.
> tutorials/TS for the New Programmer: Misc improvements

- packages/typescriptlang-org/src/lib/handbookNavigation.ts
Fixes #628 -- with a few changes from the suggestions there.
> Summary line improvements

- packages/handbook-v1/en/tutorials/TS for the New Programmer.md
Just an update to fix a grammatical error in the "TS for the New Programmer" handbook page.
> Update packages/handbook-v1/en/tutorials/TS for the New Programmer.md

- packages/handbook-v1/en/Literal Types.md
Math.random always return a value less than 1 so it was not possible to have a 6.
> Bug in roolDice function.

- packages/typescriptlang-org/src/copy/en/documentation.ts
- packages/typescriptlang-org/src/templates/pages/docs/home.tsx
Added LoopBack and Fastify to Node APIs under **Start a Project**.
> Added LoopBack and Fastify to Node APIs

- packages/handbook-v1/en/tutorials/TS for the New Programmer.md
fixes punctuation, "developersresponded" to "developers responded"
> Update TS for the New Programmer.md

- packages/handbook-v1/en/Advanced Types.md
fix broken link to basic types section
> fix broken link advanced types -> the Basic Types section

- packages/handbook-v1/en/Utility Types.md
#32964 was closed in January, so these can probably go now.
> Drop notes on this parameter related utility types

- packages/handbook-v1/en/Mixins.md
There's a type issue I see in my editor when I use `applyMixin`
I'm not sure the best way to fix this, the naive approach is to check if this value is undefined. 
It this something other people are seeing as well, or is it just my `tsconfig.json` settings?
```
Argument of type 'PropertyDescriptor | undefined' is not assignable to parameter of type 'PropertyDescriptor & ThisType<any>'.
Type 'undefined' is not assignable to type 'PropertyDescriptor & ThisType<any>'.
Type 'undefined' is not assignable to type 'PropertyDescriptor'.ts(2345)
```
> Fix "applyMixin" type issue

- packages/typescriptlang-org/src/components/layout/Sidebar.scss
- Navigation does not  follow you when you scroll down the page.
- I make the navigation sticky
- Fixes #78
> Sidebar: makes the navigation sticky

- packages/typescriptlang-org/src/components/layout/Sidebar.scss
Spacing in the button is broken.
I've fixed spacing in the button.
Fixes  #693
> Sidebar: fixed spacing button

- packages/handbook-v1/en/tutorials/React.md
react-scripts-ts is deprecated.
> Switch to typescript template in create-react-app

- packages/handbook-v1/en/tutorials/TS for Functional Programmers.md
Hi,
I added BigInt information for JS and TS.
> Update primitive types - BigInt

- packages/typescriptlang-org/src/copy/inYourLanguage.ts
- packages/typescriptlang-org/src/copy/zh/head-seo.ts
- packages/typescriptlang-org/src/copy/zh/index.ts
> Add in your language for Chinese

- packages/typescriptlang-org/src/copy/inYourLanguage.ts
Ref #805
Japanese translation for [inYourLanguage.ts](packages/typescriptlang-org/src/copy/inYourLanguage.ts)
Rebase might be needed as it could conflict with other languages changes.
- #806 
- #807 
- #808 
Thanks.
> Add ja translation for inYourLangage

- packages/typescriptlang-org/src/copy/inYourLanguage.ts
As requested in https://github.com/microsoft/TypeScript-Website/issues/805
Rebases may need to be done to conciliate other changes to the same lines (such as https://github.com/microsoft/TypeScript-Website/pull/806)
> docs(pt): translation for inYourLanguage

- packages/typescriptlang-org/src/copy/inYourLanguage.ts
References #805 
Spanish translation for `inYourLanguage.ts` file.
> docs(es): translation for inYourLanguage
