microsoft/TypeScript-Website

README.md
src/assets/scss/_global.scss
src/assets/scss/footer.scss

* Fixed cloning instructions : "TypeScript-Docs" to "TypeScript-Website"
* Fixed Star link to TypeScript's GitHub not being displayed
Before : 
After :
* Fixed footer not appearing in the bottom (for our friends that are IE users)
Before :
After :
Tested in IE, Edge, Firefox and Chrome

Fixes to README and styles

---

src/_docs/home.html

Adds Gluegun as an option, which is a toolkit for quickly building Node-powered CLIs in TypeScript.

Add Gluegun option to Node with NPM section

---

Examples/en/Playground/Language/Automatic Type Acquisition.ts

The `require` call doesn't work in TS files, and the `.ts` path was still causing errors to be reported

Removed non-imports and non-working imports from sample

---

src/assets/scss/home.scss

Banner text is not selectable, because the skyline image is above.
---
Other solution would be to move the banner text above the image:
```scss
.banner {
position: relative;
z-index: 1;
}
```

Ignore pointer events on skyline image

---

scripts/updateURLs.js

The headers used in the following function `getLatestVSExtensions` does not get reassigned.
This PR includes the change from var to const.

update type qualifier for url script headers

---

src/assets/scss/docs.scss

closes #182 
At very small sizes (below 250px) the button will now start to cover up the toc dropdown, but this seems acceptable.

Fix try-beta button

---

src/_data/community/meetups.yml

Fixes #195 
Based on other examples without a Twitter URL, this should be ok!

Remove Melbourne Typescript's incorrect Twitter URL

---

packages/create-typescript-playground-plugin/template/scripts/getDTS.js
packages/create-typescript-playground-plugin/template/tsconfig.json

Hi @orta . I'm loving Playground Plugin systems you created 😄 
In some plugins, I want to access language service methods using TypeScript worker such as:
```ts
modelChanged: (sandbox, model) => {
sandbox.getWorkerProcess.then(worker => {
return worker.getSemanticDiagnostics(model.uri.toString());
}).then(result => /* processing diagnositic */)
},
```
But for now, the `getDTS` script replaces `TypeScriptWorker` type to `any` and I can't auto-complete worker's methods.
I think it's better to fetch tsWorker.d.ts too. How about it?

make getDTS to store tsWorker.d.ts

---

packages/handbook-v1/en/Advanced Types.md

fixes #217
This section of advanced types seems to have been written during TypeScript 2.8 and was correct then. TypeScript 3.0 introduced the unknown top type making the type now `unknown` rather than `{}`
@orta the documentation is not locked to a specific version right, so should all doc follow latest TypeScript version?

fix: type mismatch #217

---

packages/typescriptlang-org/src/pages/documentation.en.tsx

As you know, there is `Starter Kits` in [Documentation](https://www.typescriptlang.org/docs/home.html) like below but it links to `Page Not Found`.
I think you probably intended to link to this page(below), but the exact same page no longer exists in React docs.
I found a page that gave a similar introduction, and changed the link to it : [Recommended Toolchains](https://reactjs.org/docs/create-a-new-react-app.html#recommended-toolchains)
The page covers a lot including `Neutrino`, `Parcel` and `Razzle`, so I believe it will be a good alternative.
Closes #143

Fix broken link about Starter Kits

---

packages/typescriptlang-org/src/pages/documentation.en.tsx

Link previously pointed to the TS in 5m overview doc.
Fixes this link:

Fix Angular link in Web Frameworks section

---

packages/playground-examples/copy/ja/TypeScript/Type Primitives/Built-in Utility Types.ts

This PR is part of #100 #220 
translated Built-in Utility Types in TypeScript playground example.
original document is here.
https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground-examples/copy/en/TypeScript/Type%20Primitives/Built-in%20Utility%20Types.ts

docs: translate Built-in utility types to Japanese

---

packages/playground-examples/copy/ja/TypeScript/Language Extensions/Enums.ts
packages/playground-examples/copy/ja/TypeScript/Language Extensions/Nominal Typing.ts
packages/playground-examples/copy/ja/TypeScript/Language Extensions/Types vs Interfaces.ts
packages/playground-examples/copy/ja/sections.json

part of #100, #220 
I translated Language Extensions playground-examples.
[![Screenshot from Gyazo](https://gyazo.com/5a489d57d2962fa4ba01ee4f30f53bf8/raw)](https://gyazo.com/5a489d57d2962fa4ba01ee4f30f53bf8)

Translate  language extensions of playground examples into japanese

---

packages/typescriptlang-org/src/copy/ja/playground.ts

Part of #100 #220 
Translated `playground.ts`
The original document can be found [here](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/typescriptlang-org/src/copy/en/playground.ts)

docs: translate configs for playground to Japanese

---

packages/typescriptlang-org/src/copy/en/documentation.ts
packages/typescriptlang-org/src/pages/documentation.en.tsx

part of #100 
Starting off some internationalization in the documentation page.

 documentation page i18n

---

packages/tsconfig-reference/copy/ja/options/allowJs.md
packages/tsconfig-reference/copy/ja/options/checkJs.md
packages/tsconfig-reference/copy/ja/options/declaration.md
packages/tsconfig-reference/copy/ja/options/declarationMap.md
packages/tsconfig-reference/copy/ja/options/jsx.md
packages/tsconfig-reference/copy/ja/options/sourceMap.md

This PR is a part of #220 
Translated tsconfig references corresponding to the following sections into Japanese:
- https://www.typescriptlang.org/v2/en/tsconfig#allowJs
- https://www.typescriptlang.org/v2/en/tsconfig#checkJs
- https://www.typescriptlang.org/v2/en/tsconfig#jsx
- https://www.typescriptlang.org/v2/en/tsconfig#declaration
- https://www.typescriptlang.org/v2/en/tsconfig#declarationMap
- https://www.typescriptlang.org/v2/en/tsconfig#sourceMap

Translate allowJs, checkJs, jsx, declaration, declarationMap, and sourcemap options into Japanese

---

packages/tsconfig-reference/copy/en/options/removeComments.md

I found this in my jp translation(#220) work and it seems that the description about `removeComment` is wrong. If tsconfig has no  `removeComments` setting, TypeScript emits original comments.

Fix removeComments config example's description.

---

packages/playground-examples/copy/en/JavaScript/Working With Classes/Mixins.ts

Removes this error:
```
Property '_scale' of exported class expression may not be private or protected.(4094)
```
https://www.typescriptlang.org/v2/en/play/?q=101#example/mixins

fix: Mixins may not specify visibility modifiers

---

packages/playground-examples/copy/es/JavaScript/External APIs/TypeScript with Deno.ts
packages/playground-examples/copy/es/JavaScript/External APIs/TypeScript with Node.js
packages/playground-examples/copy/es/JavaScript/External APIs/TypeScript with Web.js
packages/playground-examples/copy/es/JavaScript/Functions with JavaScript/Function Chaining.ts
packages/playground-examples/copy/es/JavaScript/Functions with JavaScript/Generic Functions.ts
packages/playground-examples/copy/es/JavaScript/JavaScript Essentials/Hello World.ts
packages/playground-examples/copy/es/JavaScript/JavaScript Essentials/Objects and Arrays.ts

This PR is part of #100 #232 
These are translations for some of the files in the Playground.
Original files:
- [`TypeScript with Deno.ts`](https://github.com/microsoft/TypeScript-Website/blob/v2%2Fpackages%2Fplayground-examples%2Fcopy%2Fen%2FJavaScript%2FExternal%20APIs%2FTypeScript%20with%20Deno.ts)
- [`TypeScript with Node.js`](https://github.com/microsoft/TypeScript-Website/blob/v2%2Fpackages%2Fplayground-examples%2Fcopy%2Fen%2FJavaScript%2FExternal%20APIs%2FTypeScript%20with%20Node.js)
- [`TypeScript with Web.js`](https://github.com/microsoft/TypeScript-Website/blob/v2%2Fpackages%2Fplayground-examples%2Fcopy%2Fen%2FJavaScript%2FExternal%20APIs%2FTypeScript%20with%20Web.js)
- [`Function Chaining.ts`](https://github.com/microsoft/TypeScript-Website/blob/v2%2Fpackages%2Fplayground-exampl …

Add Spanish translations for the playground

---

packages/tsconfig-reference/copy/ja/options/importHelpers.md
packages/tsconfig-reference/copy/ja/options/noEmit.md
packages/tsconfig-reference/copy/ja/options/removeComments.md
packages/tsconfig-reference/copy/ja/options/tsBuildInfoFile.md

It's a part of #220 .
I translated the following tsconfig option docs into Japanese:
- http://www.typescriptlang.org/v2/en/tsconfig#tsBuildInfoFile
- http://www.typescriptlang.org/v2/en/tsconfig#removeComments
- http://www.typescriptlang.org/v2/en/tsconfig#noEmit
- http://www.typescriptlang.org/v2/en/tsconfig#importHelpers
[![Image from Gyazo](https://i.gyazo.com/c3844edbdd78725ed104f96cd4e896b0.png)](https://gyazo.com/c3844edbdd78725ed104f96cd4e896b0)

Translate project options about code emission

---

packages/tsconfig-reference/copy/en/options/strictBindCallApply.md

I think it's better to use `twoslash` feature to explain which errors `strinctBindCallApply` option throws.
[left: before (latest v2), right: after (this PR)]

Use twoslash for example codes of "strictBindCallApply"

---

packages/typescriptlang-org/src/copy/en.ts
packages/typescriptlang-org/src/copy/en/community.ts
packages/typescriptlang-org/src/copy/es.ts
packages/typescriptlang-org/src/copy/ja.ts
packages/typescriptlang-org/src/copy/vo.ts
packages/typescriptlang-org/src/copy/zh.ts
packages/typescriptlang-org/src/templates/pages/community.tsx

part of #100 
Internationalization for the community page, submitting this live during a talk at [Wrocław TypeScript ](https://www.meetup.com/WrocTypeScript/events/sjzhvqybcdbjc/) hopefully to spark some more contributions in this site & the typescript ecosystem in general!
hopefully we see some polish translations come through 😄

community i18n

---

packages/tsconfig-reference/copy/ja/options/alwaysStrict.md
packages/tsconfig-reference/copy/ja/options/noImplicitThis.md
packages/tsconfig-reference/copy/ja/options/strictBindCallApply.md
packages/tsconfig-reference/copy/ja/options/strictPropertyInitialization.md

It's a part of #220 ( and the rest of #286  )
I translated the following options into Japanese:
- https://www.typescriptlang.org/v2/en/tsconfig#strictBindCallApply
- https://www.typescriptlang.org/v2/en/tsconfig#strictPropertyInitialization
- https://www.typescriptlang.org/v2/en/tsconfig#noImplicitThis
- https://www.typescriptlang.org/v2/en/tsconfig#alwaysStrict

Translate the latter of strict options into ja

---

packages/playground-examples/copy/ja/TypeScript/Primitives/Union and Intersection Types.ts

I translated Primitives `"Union and Intersection Types"` playground-example.
part of #220
- [Difference from original text](https://github.com/microsoft/TypeScript-Website/commit/2479023ec6e99a31637597027758b7838106b5dd)
- [www.typescriptlang.org/v2/ja/play](https://www.typescriptlang.org/v2/ja/play?#code/PTAEBUE8AcFNQK4DsCWB7JBnUBDATvDqAO46ShoBmoAJrAMYA2+KSA5qAC4AWOnuSCgCMAVg04BYAFAhQ9NAkY1QQ+AFs0BLr0EZ4nGLAB006QbigAypzys2AeTwA5BGtV5QAXlCYbd0AA+oEiu7gDcZoagAAp4aPSwmJjWfIleoABEaHBIGYGZTGiYsDQZEVLm8PY0NC5usHiYAKpIdHjgsILeAIz5AMz5AKz5AOz5AJzllaAAggCyiZiQLehdmdywjIxoeUHdgwBs+QDeoA1xeABcXHgI8AC+5dKyAJLUPPAIxRTUWTl5OFaBW2xVKoAAbthfLZ2KAUJhnmAkLBiFw0KBIAoADRyDb0ADWFAQnGusAAHjg1NBGLBLowUJwGjhGAipIjQAB1eD0QGgNQoMm0FCUSgNTr8SrYVicdFEZCrHGAmjs4i8fjEWAAci0mDI-nh2j42ng4OZdzh2D0P20RX0hkwJjZMjAUDglnotmg …

Translate Primitives "Union and Intersection Types" of playground examples into Japanese

---

packages/tsconfig-reference/copy/ja/categories/Additional_Checks_6176.md
packages/tsconfig-reference/copy/ja/options/noFallthroughCasesInSwitch.md
packages/tsconfig-reference/copy/ja/options/noImplicitReturns.md
packages/tsconfig-reference/copy/ja/options/noUnusedLocals.md
packages/tsconfig-reference/copy/ja/options/noUnusedParameters.md

It's a part of #220 .
I translated tsconfig options under https://www.typescriptlang.org/v2/en/tsconfig#Additional_Checks_6176 into Japanese.
Comparison for original docs: https://github.com/microsoft/TypeScript-Website/commit/5f84170ac5cb058e95169eb27c3e5e8c398997ae

Translate tsconfig LinterChecks options into ja

---

packages/tsconfig-reference/copy/ja/categories/Source_Map_Options_6175.md
packages/tsconfig-reference/copy/ja/options/inlineSourceMap.md
packages/tsconfig-reference/copy/ja/options/inlineSources.md
packages/tsconfig-reference/copy/ja/options/mapRoot.md
packages/tsconfig-reference/copy/ja/options/sourceRoot.md

It's a part of #220 
I translated tsconfig references under http://www.typescriptlang.org/v2/en/tsconfig#Source_Map_Options_6175 .
Comparison for original docs:
https://github.com/microsoft/TypeScript-Website/pull/302/commits/aaa46117129e2d7f2e7da19941921f7e8e6ab971

Translate tsconfig SourceMap options into ja

---

packages/tsconfig-reference/copy/en/options/plugins.md
packages/tsconfig-reference/scripts/generateJSON.ts
packages/tsconfig-reference/scripts/tsconfigRules.ts

It fixes #334 .
@orta Thanks for your advice https://github.com/microsoft/TypeScript-Website/issues/334#issuecomment-597033002
>  Let's manually set its category to Project Options in the generation script

Display "plugins" tsconfig option

---

packages/typescriptlang-org/src/templates/pages/index.tsx

Fixes the broken youtube link in this page, [https://www.typescriptlang.org/](https://www.typescriptlang.org/)
Last video in _Watch TypeScript in Action_ section.

Fix broken youtube video link (By Tj VanToll)

---

packages/handbook-v1/en/release notes/Overview.md
packages/handbook-v1/en/release notes/TypeScript 3.6.md

The current example is wrong as tslint return a sintax error.
As per TS annotation: "A 'set' accessor cannot have a return type annotation.(1095)"

Fixed sintax error in example for set and get accessor in ambient context

---

packages/handbook-v1/en/JSX.md

Changed the markdown language on JSX code blocks.
In reference to the following ticket: https://github.com/microsoft/TypeScript-Website/issues/396
**Before**
**After**
This is my first time contributing, if I've got the wrong end of the stick please let me know!

Add missing colours to jsx code blocks

---

packages/typescriptlang-org/src/templates/pages/index.scss

| Before | After |
|--------|------|
| <img width="381" alt="Screen Shot 2020-03-30 at 2 40 52 PM" src="https://user-images.githubusercontent.com/3277153/77964755-79a7fc80-7294-11ea-827b-55b83107f179.png"> | <img width="369" alt="Screen Shot 2020-03-30 at 2 40 46 PM" src="https://user-images.githubusercontent.com/3277153/77964766-7e6cb080-7294-11ea-961a-28773cde857c.png"> |

Fix next button chevron in Safari

---

packages/typescriptlang-org/src/templates/handbook.scss

Fixes the `#handbook-content` lack of stickiness when scrolling down the page in reference to https://github.com/microsoft/TypeScript-Website/issues/336
| **Before**  | **After** |
| ------------- | ------------- |
| ![336 before](https://user-images.githubusercontent.com/22731314/78041183-41043380-7325-11ea-9a3b-a8e28ee2ed18.gif)  | ![336 after](https://user-images.githubusercontent.com/22731314/78041285-5711f400-7325-11ea-8733-8c66bec72e6c.gif)  |
I noticed that the links don't highlight the correct section when clicked on, should I raise a separate issue for that?

Fix nav scrolling with page

---

packages/typescriptlang-org/src/components/layout/main.scss

Changed the colour of permalink icon in dark mode from black to white.
**Before**:
**After**:

Fix permalink icon colour in dark mode

---

packages/sandbox/src/releases.ts
packages/typescriptlang-org/src/copy/en/documentation.ts
packages/typescriptlang-org/src/copy/zh/documentation.ts
packages/typescriptlang-org/src/lib/release-info.json
packages/typescriptlang-org/src/templates/pages/docs/home.tsx

This PR adds Ember as an additional Web Framework in the `https://www.typescriptlang.org/docs/home` page. Ember both uses TS internally for large portions of its development (ember.js, glimmer-vm, etc), but also supports TypeScript for development. Ember also recently went through a huge modernization, which both simplifies the framework _and_ takes advantage of a lot of newer language features.
These changes add Ember in alphabetical order relative to the other JS frameworks (Angular, React, Vue). Additionally ensures that the blurb is translated.

Adds Ember as additional web framework

---

packages/playground-examples/copy/ja/3-7/Fixits/Big number literals.ts
packages/playground-examples/copy/ja/3-7/Fixits/Const to let.ts
packages/playground-examples/copy/ja/3-7/Fixits/Infer From Usage Changes.ts

Part of #220, 
I translated 3 playground files to Japanese.
[Big number literals.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//playground-examples/copy/en/3-7/Fixits/Big%20number%20literals.ts)
[Const to let.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//playground-examples/copy/en/3-7/Fixits/Const%20to%20let.ts)
[Infer From Usage Changes.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//playground-examples/copy/en/3-7/Fixits/Infer%20From%20Usage%20Changes.ts)

Translate 3 playground files to Japanese

---

packages/handbook-v1/en/Interfaces.md

**Page URL:** https://www.typescriptlang.org/v2/docs/handbook/interfaces.html#indexable-types
**Issue:** Mistake in code example block. `class` declaration was used, instead of `interface`.
```ts
// not class but interface
class Animal {
name: string;
}
// not class but interface
class Dog extends Animal {
breed: string;
}
// Error: indexing with a numeric string might get you a completely separate type of Animal!
interface NotOkay {
[x: number]: Animal;
[x: string]: Dog;
}
``` 
**Recommended Fix:**
```ts
interface Animal {
name: string;
}
// not class but interface
interface Dog extends Animal {
breed: string;
}
// Error: indexing with a numeric string might get you a completely separate type of Animal!
interface NotOkay {
[x: number]: Animal;
[x: string]: Dog;
}
```

fix(handbook-v1): mistake in code example block

---

packages/handbook-v1/en/The Handbook.md

The word `rush` appears twice in the same sentence, but it looks redundant.

Remove repeated word from handbook-v1 / The Handbook.md page

---

packages/typescriptlang-org/src/templates/markdown-twoslash.scss

**Warning: This was a very naive change**
Personally I prefer the more subtle outline
Before
After

Make the error pane jut out less

---

packages/typescriptlang-org/src/lib/release-plan.json

Old dates were the build dates, not the release dates https://github.com/microsoft/TypeScript/issues/37198

Update 3.9 release dates

---

.github/workflows/v2-merged.yml
package.json
packages/gatsby-remark-shiki-twoslash/package.json
yarn.lock

I was preparing to build this myself, so was pretty pleased that a simple, low dependency, TS module already existed. 
This basically runs at the end of our website deploy process and any modules which have had their version bumped gets published.

Deploys via pleb

---

src/_docs/home.html

this has already been corrected [in the v2 site](https://www.typescriptlang.org/v2/docs/home).

fix link for angular

---

packages/playground-examples/copy/es/TypeScript/Primitives/Any.ts
packages/playground-examples/copy/es/TypeScript/Primitives/Literals.ts
packages/playground-examples/copy/es/TypeScript/Primitives/Union and Intersection Types.ts
packages/playground-examples/copy/es/TypeScript/Primitives/Unknown and Never.ts

docs(es): translation of TS Primitives section

---

packages/handbook-v1/en/Compiler Options.md

Markdown link syntax fix in Compiler Options md.

Update Compiler Options.md

---

packages/typescriptlang-org/src/templates/pages/docs/home.tsx

The repo https://github.com/typescript-ruby/typescript-rails doesn't seem to be very active these days, and Rail's official JS integration has evolved in the mean time. I think it's time to switch to [Rails official TS guide](https://github.com/rails/webpacker/blob/master/docs/typescript.md).

[v2] Point the link for Ruby on Rails to the official rails/webpacker repo

---

src/_docs/home.html

Basically the same change as https://github.com/microsoft/TypeScript-Website/pull/532 but for the current master.
The repo https://github.com/typescript-ruby/typescript-rails doesn't seem to be very active these days, and Rail's official JS integration has evolved in the mean time. I think it's time to switch to [Rails official TS guide](https://github.com/rails/webpacker/blob/master/docs/typescript.md).

[v1] Point the link for Ruby on Rails to the official rails/webpacker repo

---

packages/handbook-v1/en/tutorials/Migrating from JavaScript.md

Replacement for https://github.com/microsoft/TypeScript-Handbook/pull/1315
```ts
interface Point {
distanceFromOrigin(point: Point): number;
}
Point.prototype.distanceFromOrigin = function(point: Point) {
return this.getDistance({ x: 0, y: 0});
}
```
```ts
Point.prototype.distanceFromOrigin = function(this: Point) {
return this.getDistance({ x: 0, y: 0});
}
```
Trying to make sense of what the `point: Point` is supposed to be doing. It looks like it's an argument for the function, but the function doesn't use it. I suspect it's a typo, but would love to know for sure.
This PR removes it, under the assumption that it is a typo.

Correct point example

---

packages/tsconfig-reference/copy/ja/options/include.md

This does not work.
Deviation from the English version.
https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/include.md

fix tsconfig include path

---

packages/handbook-v1/en/Module Resolution.md

I [can no longer find any documentation about `baseUrl`](https://github.com/systemjs/systemjs/search?q=baseurl&unscoped_q=baseurl).

Replace broken link to SystemJS@baseUrl

---

packages/typescriptlang-org/src/templates/pages/index.tsx

Section will get 'undefined' class if no className is provided as property
This commit fixes the issue

Fix undefined class if className is undefined

---

packages/typescriptlang-org/src/lib/oldHandbookNavigation.ts

I added `/docs/` to the href of `Template: Global Module`.
Clicking on `Template: Global Module` in the document does not jump to the corresponding page. 
After searching, it is found that the corresponding link in the source code is missing `/docs/`

Fix wrong link

---

packages/handbook-v1/en/Interfaces.md

There seem to a few issues with this code, comments, and descriptions. I took a stab at fixing them. (But I'm brand new to TypeScript, so I might be interpreting it incorrectly).
The Location class doesn't seem to have anything to do with the rest of the example code, and it also throws an unrelated error "Duplicate identifier 'Location'.", which is confusing.
The comment on line 655 also seems incorrect - it seems vestigial from some previous iteration of code. The actual error shown is: "Class 'ImageControl' incorrectly implements interface 'SelectableControl'.  Types have separate declarations of a private property 'state'."

Remove Location and clarify ImageControl error

---

packages/playground-examples/copy/en/JavaScript/Modern JavaScript/JSDoc Support.js

Hello,
I think there's a missing closing brace in the JSDoc Support code example.
```js
/** @typedef {{owner: User, name: string} Resource */
```
I fixed it by adding the brace.
```js
/** @typedef {{owner: User, name: string}} Resource */
```

Add the missing closing brace in JSDoc Example

---

packages/handbook-v1/en/declaration files/Do's and Don'ts.md

For whatever reason, this link had an extra `-` which caused it to not match the anchor on the page.

Fixes dead link.

---

packages/handbook-v1/en/declaration files/Do's and Don'ts.md

Feedback definitely welcome for this section.  I tried to give a brief, but not too long-winded, overview of why it is a problem and provide the most common workaround (`unknown`) but I'm sure this could be improved.

Adds a section recommending against the usage of `any`.

---

packages/handbook-v1/en/Utility Types.md

I added links to the `this` and `unknown` documentation in the description of utility types

Link to "this" documentation in utility types

---

packages/handbook-v1/en/tutorials/TS for JS Programmers.md

From the name of the 'getLength' function it looks like it was intended to return 'obj.length' and not just 'obj'.

Update getLength function example to return length

---

packages/handbook-v1/en/Basic Types.md

[Since typescript 3.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html), ts supports a number type called `bigint` but the handbook says that the only numeric type supported is `number`. This PR fixes that.

Explain bigint type in handbook

---

packages/typescriptlang-org/src/components/index/EditorExamples.tsx

There are some extra spaces in the TypeScript `addPrices()` example on the main TypeScript website.
Current:
PR changes:

Remove extra prepended spaces in addPrices() example

---

packages/gatsby-remark-shiki-twoslash/src/dom.ts

As promised, part 1 of https://twitter.com/orta/status/1262782512260136962
The implementation can definitely be optimized as we're executing `getBoundingClientRect` to the parent node every time even though it probably never changes. But it works for now and I didn't notice any performance issue.
**Before**
**After**

Limit tooltip width in gatsby-remark-shiki-twoslash

---

packages/handbook-v1/en/release notes/TypeScript 1.7.md

This does not exit any more:
http://blogs.msdn.com/b/typescript/archive/2015/11/03/what-about-async-await.aspx

Updated broken link

---

packages/handbook-v1/en/tutorials/TS for Functional Programmers.md

There is no additional `.` in this syntax. I think the sentence was intended to refer to the parentheses (otherwise 1. looks like the beginning of a floating-point number literal)?

Fix mistake in TS for Functional Programmers doc

---

src/index.html

remove "js" postfix from "angular" reference on landing page

---

packages/typescriptlang-org/src/copy/es.ts

This solves the issue of spanish text on website index not being displayed. @orta

fix: quick fix index path on spanish docs

---

packages/handbook-v1/en/Advanced Types.md

fix small typo in advanced types

fix typo `object['42'`] -> `object['42']`

---

packages/handbook-v1/en/tutorials/React.md

The Dispatch symbol is no longer exported from react-redux, instead import it directly from redux.

Dispatch is no longer part of the react-redux library

---

packages/sandbox/src/typeAcquisition.ts
packages/typescriptlang-org/src/pages/dev/twoslash.tsx

The playground `debugger` gets in my way frequently since I like to keep devtools open while in the playground and this triggers on almost every character typed when importing modules. The twoslash call was removed for completeness.

fix: Remove debugger calls

---

packages/handbook-v1/en/Advanced Types.md

- update code samples to match the rest of the samples
- use compiler exact error messages (if someone searches those keywords)
- minor typo fix in line [669](https://github.com/microsoft/TypeScript-Website/compare/v2...kaznovac:code-samples-consistency#diff-a2c92f1db92017f034fd32ed99788828L669)

code style consistency, use exact error messages, minor typo fix

---

packages/typescriptlang-org/src/templates/markdown-twoslash.scss

Made the twoslash tooltip not flicker when hovering the cursor on the border

Fix twoslash tooltip flicker on border hover

---

packages/gatsby-remark-shiki-twoslash/package.json
packages/playground-examples/scripts/generateTOC.js
packages/typescript-vfs/package.json
packages/typescriptlang-org/lib/bootup/ingestion/createPlaygroundExamplePages.ts
packages/typescriptlang-org/package.json
yarn.lock

I had to do 2 fixes to make `yarn bootstrap` work
1. Git should have files saved as LF so `os.EOL` doesn't work. Switching to just "\n" works.
1. cp does not exists on windows, cpy-cli can fix this. (happy to use any other package)

chore: fix bootstrap on windows

---

packages/handbook-v1/en/tutorials/React.md

The createStore function have been expanded to take four template arguments, and the initial state injection have been moved to the reducer.
See this answer for reference https://stackoverflow.com/a/60884430/131697

make the tutorial compatible with redux 4

---

packages/gatsby-remark-shiki-twoslash/package.json
packages/ts-twoslasher/package.json
packages/ts-twoslasher/src/index.ts
packages/typescriptlang-org/package.json
yarn.lock

In twoslash, you can only set `noErrors` and `showEmit` to `false` in `defaultOptions`. I changed that to `boolean` and also fixed a small typo in the doc comment.

Make it possible to set noErrors and showEmit to true

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.huskyrc.js
.vscode/extensions.json
packages/ts-twoslasher/README.md

GH Codespaces is out for a lot of people (including me) and one of the cool features it has is too apply custom configs to different repos. 
I thought this could make the onboarding process easier, so I created the `.devcontainer` folder following [the default TS container template from MS](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/typescript-node-14) to integrate in codespaces.
This container:
- Comes with Node 14 and TS
- Install yarn globally
- Installs Code Spell Checker extension for translating purposes
- It'd be nice to suggest other extensions based on the language the person is translating/using
- Runs `yarn install` and `yarn bootstrap` after start
- Forwards port `8000` to the client

Adds custom config for GitHub CodeSpaces

---

.github/workflows/CI.yml
packages/gatsby-remark-shiki-twoslash/package.json
packages/gatsby-remark-shiki-twoslash/src/index.ts
packages/ts-twoslasher/README.md
packages/ts-twoslasher/package.json
packages/ts-twoslasher/scripts/inline-results.js
packages/ts-twoslasher/src/index.ts
packages/ts-twoslasher/test/compiler_options.test.ts
packages/ts-twoslasher/test/modules.test.ts
packages/typescriptlang-org/package.json
packages/typescriptlang-org/src/pages/dev/bug-workbench.tsx
packages/typescriptlang-org/src/pages/dev/twoslash.tsx

After the conversation on Discord, here's the change that converts the `twoslasher` parameters to an options object. I also added the compilerOptions option.

change twoslasher to take an options object, add compilerOptions option

---

packages/handbook-v1/en/Basic Types.md

I created a new suggestion for adding `unknown` based on #742. It adds `unknown` as basic type to the handbook. I combined parts of the original version and parts of #742 and rearranged them. I moved the section about `unknown` and `any` next to each other to provide a direct comparison.
PS: While editing the document, I was wondering if `unknown` has the same properties as `Object | null | undefined`.

Adds unknown as a basic type

---

packages/gatsby-remark-shiki-twoslash/package.json
packages/ts-twoslasher/README.md
packages/ts-twoslasher/package.json
packages/ts-twoslasher/src/index.ts
packages/ts-twoslasher/test/custom_transformers.test.ts
packages/typescript-vfs/package.json
packages/typescript-vfs/src/index.ts
packages/typescriptlang-org/package.json

This adds support for passing custom transformers, in the same object form (`before`/`after`/`afterDeclarations`) as you'd pass to `Program#emit` and friends, as a new configuration option named `customTransformers`.

twoslash: add support for custom transformers

---

packages/playground-examples/copy/es/TypeScript/Meta-Types/Conditional Types.ts
packages/playground-examples/copy/es/TypeScript/Meta-Types/Discriminate Types.ts
packages/playground-examples/copy/es/TypeScript/Meta-Types/Indexed Types.ts
packages/playground-examples/copy/es/TypeScript/Meta-Types/Mapped Types.ts

References #232
- **TypeScript** -> **Meta-Types Section**

docs(es): translation of TypeScript Meta-Types section

---

packages/documentation/copy/en/Utility Types.md
packages/playground-examples/copy/en/3-8/Breaking Changes/Checking Unions with Index Signatures.ts

**Page URL:** 
- handbook(Utility Types)
- https://www.staging-typescript.org/docs/handbook/utility-types.html
- playground(Checking Unions with Index Signatures)
- https://www.staging-typescript.org/play/?ts=3.8.3&q=413#example/checking-unions-with-index-signatures
**Changes:**
- Fixed some wrong types on Utility Types.
- Here is a playground link what I've checked.
- https://www.staging-typescript.org/play?#code/C4TwDgpgBAKgjFAvFAwgewHYGdgCcCuAxsGrgAoCGuFAthMBLlgDwBKEA5gKIAeY62PERK4AfAG4oAeilQA2jlwBLDBwA0UABSKVHKAB8o+DABMIAMxUQTASgD8AXQCQAKFCRYAJiRR2wfLgYMOAQzBgQAG6MEtKyFBggru7QMADMPgCSgvGEEMGQYZHRkjJQ8YlAA
- Fixed a comment of Checking Unions with Index Signatures.
- ref: https://github.com/microsoft/TypeScript-Website/pull/797#discussion_r460385401
Thanks.

Fix some comments on handbook and playground

---

packages/playground-examples/copy/ja/3-8/Breaking Changes/Checking Unions with Index Signatures.ts

Part of #220 
`Checking Unions with Index Signatures.ts`
- Original doc
- [Checking Unions with Index Signatures.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//playground-examples/copy/en/3-8/Breaking%20Changes/Checking%20Unions%20with%20Index%20Signatures.ts?rgh-link-date=2020-02-06T15%3A46%3A01Z)
- Diff
- https://github.com/microsoft/TypeScript-Website/commit/b5e0fdbe45692128baf6089b4b82f286fd931f48

Translate  playground example (3.8 breaking changes) into ja

---

packages/typescriptlang-org/src/components/layout/main.scss

use [`color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) in dark theme to improve scrollbar appearance
before:
after:

Improve scrollbar appearance in dark theme
